/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitiosRouteImport } from './routes/sitios'
import { Route as CargaRouteImport } from './routes/carga'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDevicesUpsertRouteImport } from './routes/api/public/devices/upsert'

const SitiosRoute = SitiosRouteImport.update({
  id: '/sitios',
  path: '/sitios',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaRoute = CargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevicesUpsertRoute = ApiPublicDevicesUpsertRouteImport.update({
  id: '/api/public/devices/upsert',
  path: '/api/public/devices/upsert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/sitios': typeof SitiosRoute
  '/api/public/devices/upsert': typeof ApiPublicDevicesUpsertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/sitios': typeof SitiosRoute
  '/api/public/devices/upsert': typeof ApiPublicDevicesUpsertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/sitios': typeof SitiosRoute
  '/api/public/devices/upsert': typeof ApiPublicDevicesUpsertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carga' | '/sitios' | '/api/public/devices/upsert'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carga' | '/sitios' | '/api/public/devices/upsert'
  id: '__root__' | '/' | '/carga' | '/sitios' | '/api/public/devices/upsert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargaRoute: typeof CargaRoute
  SitiosRoute: typeof SitiosRoute
  ApiPublicDevicesUpsertRoute: typeof ApiPublicDevicesUpsertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitios': {
      id: '/sitios'
      path: '/sitios'
      fullPath: '/sitios'
      preLoaderRoute: typeof SitiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga': {
      id: '/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof CargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/upsert': {
      id: '/api/public/devices/upsert'
      path: '/api/public/devices/upsert'
      fullPath: '/api/public/devices/upsert'
      preLoaderRoute: typeof ApiPublicDevicesUpsertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargaRoute: CargaRoute,
  SitiosRoute: SitiosRoute,
  ApiPublicDevicesUpsertRoute: ApiPublicDevicesUpsertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
